version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org/
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    timezone: Africa/Casablanca
  open-pull-requests-limit: 10
  labels:
  - bump
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  registries:
  - npm-registry-registry-npmjs-org
